DROP TABLE IF EXISTS AMET;
CREATE TABLE AMET(
    localidad VARCHAR(255) PRIMARY KEY,
    provincia VARCHAR(255),
    temp_max DECIMAL(10,2),
    h_temp_max TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    temp_min DECIMAL(10,2),
    h_temp_min TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
